/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/wallet/faucet": {
    /**
     * Generates a new wallet and funds it
     * @description Generates a new wallet and funds it on the selected network
     */
    get: operations["generate_faucet_wallet"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      error?: string;
    };
    Account: {
      classic_address: string;
      address?: string;
      xaddress?: string;
      secret?: string;
    };
    Faucet: {
      account: components["schemas"]["Account"];
      /** Format: int32 */
      amount: number;
      /** Format: int32 */
      balance?: number;
      trace?: components["schemas"]["Trace"];
    };
    Trace: {
      /** Format: hash */
      hash?: string;
      code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Generates a new wallet and funds it
   * @description Generates a new wallet and funds it on the selected network
   */
  generate_faucet_wallet: {
    responses: {
      /** @description successfully generated a new faucet wallet */
      200: {
        content: {
          "application/json": components["schemas"]["Faucet"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
